[package]
name    = "imgscrpr"
version = "0.3.0"
authors = ["jinyeow <jin-yeow@outlook.com>"]

[dependencies]
clap       = "2.29.2"
regex      = "*"
reqwest    = "*"
scraper    = "*"
serde_json = "*"
url        = "*"
